### PR TITLE
Fix token dragging in Firefox

### LINKED ISSUE #54: Dragging tokens in Firefox leaves them in weird locations
Thanks Tom 🙄

### PR DESCRIPTION
**Pull request by cpytel**
Fixes #54

`clientX` and `clientY` are always set to 0 in Firefox on the drag event.

This is a bug in Firefox that has been open for 11 years
(https://bugzilla.mozilla.org/show_bug.cgi?id=505521).

We can get `clientX` and `clientY` in drag start, and by setting a
`dragover` handler on the entire map. To workaround this we set `clientX`
and `clientY` in the data of the map and use that instead of the
`clientX` and `clientY` from the `drag` event.

### CODE REVIEW

**Comment by cpytel** [comment]
Consider this more of a spike for right now. This works in Safari, Firefox, and Chrome but it broke the specs. Going for a run now, but will pick this back up later. Let me know if you have any thoughts.

File: app/javascript/controllers/map_controller.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ export default class extends Controller {
   }
 
   mapPositionOf(event) {
-    const { clientX, clientY } = event
+    const { clientX, clientY } = this.currentMapTarget.dataset
```
Comment (jdbann) [inline app/javascript/controllers/map_controller.js:33]: This is also used to work out the the pointer location so probably better to build a custom event to pass in here instead.

**Comment by cpytel** [comment]
Ok, as noted on the issue, this is a workaround for the issue with firefox. It doesn't look like there are any other issues with Firefox.

I tried using selenium's `drag_and_drop_by` https://www.selenium.dev/documentation/en/support_packages/mouse_and_keyboard_actions_in_detail/#draganddropby which appears to be exactly what we want to replace our custom specs, but it appears to have the same problem - it fires mouse events and doesn't fire `dragover`.

**Comment by jdbann** [comment]
> I tried using selenium's drag_and_drop_by https://www.selenium.dev/documentation/en/support_packages/mouse_and_keyboard_actions_in_detail/#draganddropby which appears to be exactly what we want to replace our custom specs, but it appears to have the same problem - it fires mouse events and doesn't fire dragover.

Yeah, there's no actual mouse emulation! It's a real pain.

**Comment by jdbann** [comment]
I've just done some testing myself, and two things are very interesting:

- Multiple actions for the same event an element are fired from left to right - so `data-actions="mousedown->map#actionOne mousedown->map#actionTwo"` will fire `actionOne` then `actionTwo` [PR](https://github.com/stimulusjs/stimulus/pull/149)
- The same event is passed from one element to the next, so it can be augmented with extra data

With that in mind, we could create a `DragFixController` which adds `ondragover` to `window` then add an action to any element which uses the drag event:

```js
export default class extends Controller {
  storeClientCoords({clientX, clientY}) {
    this.element.dataset.clientX = clientX
    this.element.dataset.clientY = clientY
  }

  fixDragEvent(event) {
    event.clientX = this.element.clientX
    event.clientY = this.element.clientY
  }
}
```

```html
<div class="token" data-action="drag->dragFix#fixDragEvent drag->map#moveToken">
```

**Comment by cpytel** [comment]
That's cool. I'm inclined to continue with drag and drop if we can, and all this doesn't seem _too_ cumbersome, especially if we don't hit more problems in the future. What do you think?

**Comment by jdbann** [comment]
If one of the approaches we have here works well enough then lets stick with drag and drop.

I can imagine us really pushing the limits of what it is capable of though, so finding ways to patch the behaviour of the API without changing the feature code will make sure we always have a way out. Apart from the `dataTransfer` stuff I think you could swap what we currently have for mouse events and it would still work.

**Comment by cpytel** [comment]
I've tried your suggestion in https://github.com/jdbann/table/tree/global-drag-fix and unfortunately, I get the error `TypeError: Attempted to assign to readonly property.`

Screen Shot 2020-05-09 at 4 03 30 PM

It looks like we can't modify those properties on the event.

So it looks like we could still introduce this controller if we wanted, which would move the storing of the client coordinates out of the map controller, but then we'd still need to use the specially stored coordinates, rather than get them from the event.

**Comment by jdbann** [comment]
Could we create a new event?

**Comment by cpytel** [comment]
Do you mean a new fake drag event that is a copy of the other one but with `clientX` and `clientY` set?

I'm concerned, perhaps incorrectly, about doing that because it seems really invasive for what we're trying to do, and it seems like that could come back to cause us trouble down the road. Using the regular events we know all browsers give us in fairly normal ways like this PR is currently doing makes me more comfortable.

I think if we really need to start messing around, then we should consider going back to regular mouse events from drag and drop.

What do you think?

**Comment by jdbann** [comment]
> Do you mean a new fake drag event that is a copy of the other one but with clientX and clientY set?

Yeah, rebuild the original event with the correct values. The ideal solution for me would be treating this as a polyfill. We have a clear understanding of how the drag and drop API should work so lets get all browsers to match up to that standard 😝

It just feels like a completely different layer which transforms the incorrect Firefox event into the expected event. I'd even go so far as to say this could be some kind of plugin for Turbolinks which applies to all `drag` events.

**Comment by jdbann** [comment]
Surprising myself by having so many frontend opinions!

**Comment by cpytel** [comment]
I think if you'd like to explore that you should pick up the code to see how it works and whether it's better. I'm skeptical about sinking more time or special workarounds into fixing Firefox bugs, but I'm happy if you want to do it =)

This PR is a working fix to the problem in Firefox, and we can come back to it if you decide you're not happy with the other approach.

**Comment by jdbann** [comment]
Yeah my attempt was a hacky mess. Apologies for pushing that approach

**Comment by cpytel** [comment]
No worries! :)
